# Generated by Django 4.0.5 on 2022-06-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_is_admin_alter_account_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sex',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
