# Generated by Django 4.0.5 on 2022-06-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_pagesmodel_options_pagesmodel_date_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesmodel',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pagesmodel',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pagesmodel',
            name='body_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pagesmodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pagesmodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pagesmodel',
            name='title_uz',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
