# Generated by Django 4.0.5 on 2022-06-22 04:10

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_pagesmodel_body_en_pagesmodel_body_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesmodel',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_location),
        ),
        migrations.AddField(
            model_name='pagesmodel',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_location),
        ),
        migrations.AddField(
            model_name='pagesmodel',
            name='image_uz',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_location),
        ),
    ]
