# Generated by Django 4.0.5 on 2022-06-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_pagesmodel_image_en_pagesmodel_image_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
